// カテゴリボーナス設定
export const categoryBonusConfig = {
    china: { name: "中華料理開発お祝い", perCount: 500 },
    america: { name: "アメリカン開発お祝い", perCount: 1500 },
    italy: { name: "イタリアン開発お祝い", perCount: 4000 },
    sweet: { name: "スイーツ開発お祝い", perCount: 10000 },
    asia: { name: "アジアン開発お祝い", perCount: 30000 },
    europe: { name: "ヨーロピアン開発お祝い", perCount: 100000 },
    space: { name: "宇宙グルメ開発お祝い", perCount: 300000 }
};

// ショップカテゴリ
export const shopCategories = [
    { id: "japan", name: "日本食", cost: 0, icon: "🍱", desc: "初期解放済みの馴染み深い和食" },
    { id: "china", name: "中華料理", cost: 150000, icon: "🐼", desc: "開発メリット：1皿ごとに【＋￥500】加算！" },
    { id: "america", name: "アメリカン", cost: 500000, icon: "🍔", desc: "開発メリット：1皿ごとに【＋￥1,500】加算！" },
    { id: "italy", name: "イタリアン", cost: 1500000, icon: "🍕", desc: "開発メリット：1皿ごとに【＋￥4,000】加算！" },
    { id: "sweet", name: "スイーツ・カフェ", cost: 5000000, icon: "🍰", desc: "開発メリット：1皿ごとに【＋￥10,000】加算！" },
    { id: "asia", name: "アジアンエスニック", cost: 15000000, icon: "🐘", desc: "開発メリット：1皿ごとに【＋￥30,000】加算！" },
    { id: "europe", name: "ヨーロピアン", cost: 40000000, icon: "🏰", desc: "開発メリット：1皿ごとに【＋￥100,000】加算！" },
    { id: "space", name: "宇宙の謎グルメ", cost: 100000000, icon: "🛸", desc: "開発メリット：1皿ごとに【＋￥300,000】加算！" }
];

// スキルデータ
export const skillData = [
    { id: "apron", name: "ふかふかエプロン", icon: "🛡️", desc: "タイピングミスを確率で無効化（ガード）する", costs: [20000, 50000, 120000, 300000, 800000], effects: ["なし", "10%でガード", "20%でガード", "30%でガード", "40%でガード", "50%でガード"] },
    { id: "hourglass", name: "秘密の砂時計", icon: "⏱️", desc: "ゲームの初期制限時間が永続的に伸びる", costs: [30000, 80000, 200000, 500000, 1200000], effects: ["60秒", "+2秒", "+4秒", "+6秒", "+8秒", "+10秒"] },
    { id: "pan", name: "黄金のフライパン", icon: "🍳", desc: "料理の獲得売上(小計)に永続ボーナス", costs: [50000, 150000, 400000, 1000000, 2500000], effects: ["1.0倍", "1.1倍ボーナス", "1.2倍ボーナス", "1.3倍ボーナス", "1.4倍ボーナス", "1.5倍ボーナス"] },
    { id: "megaphone", name: "呼び込みメガホン", icon: "📢", desc: "文字数が多くて高額な料理が出現しやすくなる", costs: [40000, 100000, 250000, 600000, 1500000], effects: ["通常通り", "長文確率少しUP", "長文確率UP", "長文確率かなりUP", "長文確率大UP", "高級長文メニュー確定!!"] }
];

// 消費アイテムデータ
export const consumableData = [
    { id: "drink", name: "もっちゃ栄養ドリンク", icon: "🧪", cost: 15000, desc: "次の1ゲームのみ、文字入力時のコンボ上昇値が2倍になる！" },
    { id: "curry", name: "まかないの激辛カレー", icon: "🍛", cost: 25000, desc: "次の1ゲームのみ、ミスした時の時間減少ペナルティが0.5秒に半減！" },
    { id: "bento", name: "もっちゃ特製お弁当箱", icon: "🍱", cost: 50000, desc: "次の1ゲームのみ、レシート末尾の【新メニュー開発ボーナス】がすべて1.5倍に跳ね上がる！" }
];

// トロフィー設定
export const trophyConfig = [
    { name: "ブロンズもっちゃ像", icon: "🥉", desc: "1ゲームの売上が￥10,000に到達する" },
    { name: "シルバーもっちゃ像", icon: "🥈", desc: "1ゲームの売上が￥100,000に到達する" },
    { name: "ゴールドもっちゃ像", icon: "🥇", desc: "累計売上が￥1,000,000を突破する" },
    { name: "コンボマスターリボン", icon: "🎀", desc: "1ゲーム中に「20連続コンボ」以上を達成する" },
    { name: "一流料理人のコック帽", icon: "👨‍🍳", desc: "ミス3回以下かつ、1ゲームで30皿以上提供する" },
    { name: "もっちゃ天帝の王冠", icon: "👑", desc: "1ゲームの売上が￥1,000,000に到達する（天帝の証）" }
];

// ガチャ設定とキャラクターデータ (画像パスを assets/img/ に変更済)
export const GACHA_COST = 50000;
export const marmotData = [
    { id: "default", name: "ノーマルもっちゃ", icon: "🐹", normal: "assets/img/normal.png", eat: "assets/img/image_1.png", miss: "assets/img/shout.png", isDefault: true },
    { id: "marmot_berry", name: "ベリーマーモット", icon: "🍓", normal: "assets/img/marmot_berry_normal.png", eat: "assets/img/marmot_berry_eat.png", miss: "assets/img/marmot_berry_miss.png" },
    { id: "marmot_chef", name: "コックマーモット", icon: "👨‍🍳", normal: "assets/img/marmot_chef_normal.png", eat: "assets/img/marmot_chef_eat.png", miss: "assets/img/marmot_chef_miss.png" },
    { id: "marmot_princess", name: "プリンセスマーモット", icon: "👑", normal: "assets/img/marmot_princess_normal.png", eat: "assets/img/marmot_princess_eat.png", miss: "assets/img/marmot_princess_miss.png" },
    { id: "marmot_ninja", name: "忍者マーモット", icon: "🥷", normal: "assets/img/marmot_ninja_normal.png", eat: "assets/img/marmot_ninja_eat.png", miss: "assets/img/marmot_ninja_miss.png" },
    { id: "marmot_astro", name: "宇宙飛行士マーモット", icon: "🧑‍🚀", normal: "assets/img/marmot_astro_normal.png", eat: "assets/img/marmot_astro_eat.png", miss: "assets/img/marmot_astro_miss.png" },
    { id: "marmot_new1", name: "ニューマーモット", icon: "⭐", normal: "assets/img/marmot_new1_normal.png", eat: "assets/img/marmot_new1_eat.png", miss: "assets/img/marmot_new1_miss.png" }
];
export const gachaPool = marmotData.filter(m => !m.isDefault);

// 単語リスト
export const wordList = [
    // 日本食 (japan)
    { category: "japan", ja: "おにぎり", romaji: "onigiri" },
    { category: "japan", ja: "みそ汁", romaji: "misoshiru" },
    { category: "japan", ja: "お寿司", romaji: "osushi" },
    { category: "japan", ja: "うどん", romaji: "udon" },
    { category: "japan", ja: "おでん", romaji: "oden" },
    { category: "japan", ja: "すき焼き", romaji: "sukiyaki" },
    { category: "japan", ja: "天ぷら", romaji: "tenpura" },
    { category: "japan", ja: "牛丼", romaji: "gyuudon" },
    { category: "japan", ja: "そば", romaji: "soba" },
    { category: "japan", ja: "親子丼", romaji: "oyakodon" },
    { category: "japan", ja: "カツ丼", romaji: "katsudon" },
    { category: "japan", ja: "天丼", romaji: "tendon" },
    { category: "japan", ja: "豚汁", romaji: "tonjiru" },
    { category: "japan", ja: "生姜焼き", romaji: "shougayaki" },
    { category: "japan", ja: "肉じゃが", romaji: "nikujaga" },
    { category: "japan", ja: "筑前煮", romaji: "chikuzenni" },
    { category: "japan", ja: "焼き魚", romaji: "yakizakana" },
    { category: "japan", ja: "刺身", romaji: "sashimi" },
    { category: "japan", ja: "ちらし寿司", romaji: "chirashizushi" },
    { category: "japan", ja: "茶碗蒸し", romaji: "chawanmushi" },
    { category: "japan", ja: "焼き鳥", romaji: "yakitori" },
    { category: "japan", ja: "とんかつ", romaji: "tonkatsu" },
    { category: "japan", ja: "冷や奴", romaji: "hiyayakko" },
    { category: "japan", ja: "きつねうどん", romaji: "kitsuneudon" },
    { category: "japan", ja: "天ぷらそば", romaji: "tenpurasoba" },
    { category: "japan", ja: "うな重", romaji: "unajuu" },
    { category: "japan", ja: "卵かけご飯", romaji: "tamagokakegohan" },
    { category: "japan", ja: "いなり寿司", romaji: "inarizushi" },
    { category: "japan", ja: "冷やし中華", romaji: "hiyashichuuka" },
    { category: "japan", ja: "鯛の塩焼き", romaji: "tainoshioyaki" },
    { category: "japan", ja: "茶漬け", romaji: "chazuke" },
    { category: "japan", ja: "納豆ご飯", romaji: "nattougohan" },
    { category: "japan", ja: "鯖の味噌煮", romaji: "sabanomisoni" },
    { category: "japan", ja: "出し巻き卵", romaji: "dashimakitamago" },
    { category: "japan", ja: "そぼろ丼", romaji: "soborodon" },

    // 中華料理 (china)
    { category: "china", ja: "ラーメン", romaji: "ra-men" },
    { category: "china", ja: "ギョーザ", romaji: "gyo-za" },
    { category: "china", ja: "チャーハン", romaji: "cha-han" },
    { category: "china", ja: "肉まん", romaji: "nikuman" },
    { category: "china", ja: "小籠包", romaji: "shouronpou" },
    { category: "china", ja: "麻婆豆腐", romaji: "ma-bo-doufu" },
    { category: "china", ja: "回鍋肉", romaji: "hoikorou" },
    { category: "china", ja: "酢豚", romaji: "subuta" },
    { category: "china", ja: "ごま団子", romaji: "gomadango" },
    { category: "china", ja: "杏仁豆腐", romaji: "annindoufu" },
    { category: "china", ja: "エビチリ", romaji: "ebichiri" },
    { category: "china", ja: "青椒肉絲", romaji: "chinjaoro-su" },
    { category: "china", ja: "担々麺", romaji: "tantanmen" },
    { category: "china", ja: "天津飯", romaji: "tenshinhan" },
    { category: "china", ja: "春巻き", romaji: "harumaki" },
    { category: "china", ja: "シュウマイ", romaji: "shuumai" },
    { category: "china", ja: "北京ダック", romaji: "pekindakku" },
    { category: "china", ja: "油淋鶏", romaji: "yuurinchii" },
    { category: "china", ja: "エビマヨ", romaji: "ebimayo" },
    { category: "china", ja: "酸辣湯", romaji: "sanra-tan" },
    { category: "china", ja: "ワンタン麺", romaji: "wantanmen" },
    { category: "china", ja: "ジャージャー麺", romaji: "ja-ja-men" },
    { category: "china", ja: "麻婆茄子", romaji: "ma-bo-nasu" },
    { category: "china", ja: "八宝菜", romaji: "happousai" },
    { category: "china", ja: "棒棒鶏", romaji: "banbanji-" },
    { category: "china", ja: "フカヒレスープ", romaji: "fukahiresu-pu" },
    { category: "china", ja: "カニ玉", romaji: "kanitama" },
    { category: "china", ja: "ちまき", romaji: "chimaki" },
    { category: "china", ja: "水餃子", romaji: "suigyouza" },
    { category: "china", ja: "小豆粥", romaji: "azukigayu" },
    { category: "china", ja: "油条", romaji: "yu-jau" },
    { category: "china", ja: "マンゴープリン", romaji: "mango-purin" },
    { category: "china", ja: "烏龍茶ゼリー", romaji: "u-ronchazeri-" },

    // アメリカン (america)
    { category: "america", ja: "ハンバーグ", romaji: "hanba-gu" },
    { category: "america", ja: "フライドポテト", romaji: "furaidopoteto" },
    { category: "america", ja: "ハンバーガー", romaji: "hanba-ga-" },
    { category: "america", ja: "ステーキ", romaji: "sute-ki" },
    { category: "america", ja: "チキンナゲット", romaji: "chikinnagetto" },
    { category: "america", ja: "ポップコーン", romaji: "poppuko-n" },
    { category: "america", ja: "ポテトチップス", romaji: "potetochippusu" },
    { category: "america", ja: "ホットドッグ", romaji: "hottodoggu" },
    { category: "america", ja: "バーベキューリブ", romaji: "ba-bekyu-ribu" },
    { category: "america", ja: "オニオンリング", romaji: "onionringu" },
    { category: "america", ja: "バッファローチキン", romaji: "baffaro-chikin" },
    { category: "america", ja: "マカロニチーズ", romaji: "makaronichi-zu" },
    { category: "america", ja: "コールスロー", romaji: "ko-rusuro-" },
    { category: "america", ja: "チーズバーガー", romaji: "chi-zuba-ga-" },
    { category: "america", ja: "フライドチキン", romaji: "furaidochikin" },
    { category: "america", ja: "チョコチップクッキー", romaji: "chokochippukukki-" },
    { category: "america", ja: "ブラウニー", romaji: "burauni-" },
    { category: "america", ja: "クラムチャウダー", romaji: "kuramuchauda-" },
    { category: "america", ja: "パンプキンパイ", romaji: "panpukinpai" },
    { category: "america", ja: "マuffin", romaji: "mafin" },
    { category: "america", ja: "ベーグル", romaji: "be-guru" },
    { category: "america", ja: "ミートローフ", romaji: "mi-toro-fu" },
    { category: "america", ja: "プルドポーク", romaji: "purudopo-ku" },
    { category: "america", ja: "チリコンカン", romaji: "chirikonkan" },
    { category: "america", ja: "パンケーキ", romaji: "panke-ki" },
    { category: "america", ja: "ドーナツ", romaji: "do-natsu" },
    { category: "america", ja: "ハッシュポテト", romaji: "hasshupoteto" },
    { category: "america", ja: "ビスケット", romaji: "bisuketto" },
    { category: "america", ja: "チーズカーズ", romaji: "chi-zuka-zu" },
    { category: "america", ja: "ルートビア", romaji: "ru-tobia" },
    { category: "america", ja: "サンデー", romaji: "sande-" },

    // イタリアン (italy)
    { category: "italy", ja: "オムライス", romaji: "omuraisu" },
    { category: "italy", ja: "ピザ", romaji: "piza" },
    { category: "italy", ja: "スパゲッティ", romaji: "supagetti" },
    { category: "italy", ja: "グラタン", romaji: "guratan" },
    { category: "italy", ja: "オムレツ", romaji: "omuretsu" },
    { category: "italy", ja: "ナポリタン", romaji: "naporitan" },
    { category: "italy", ja: "カルボナーラ", romaji: "karubona-ra" },
    { category: "italy", ja: "ドリア", romaji: "doria" },
    { category: "italy", ja: "ラザニア", romaji: "razania" },
    { category: "italy", ja: "マルゲリータ", romaji: "marugeri-ta" },
    { category: "italy", ja: "ペペロンチーノ", romaji: "peperonchi-no" },
    { category: "italy", ja: "ジェノべーゼ", romaji: "jenobe-ze" },
    { category: "italy", ja: "ミートソース", romaji: "mi-toso-su" },
    { category: "italy", ja: "リゾット", romaji: "rizotto" },
    { category: "italy", ja: "ミネストローネ", romaji: "minesturo-ne" },
    { category: "italy", ja: "カプレーゼ", romaji: "kapure-ze" },
    { category: "italy", ja: "ティラミス", romaji: "tiramisu" },
    { category: "italy", ja: "パンナコッタ", romaji: "pannakotta" },
    { category: "italy", ja: "フォカッチャ", romaji: "fokaccya" },
    { category: "italy", ja: "ブルスケッタ", romaji: "burusuketta" },
    { category: "italy", ja: "ボロネーゼ", romaji: "borone-ze" },
    { category: "italy", ja: "ボンゴレビアンコ", romaji: "bongorebianko" },
    { category: "italy", ja: "ペンネアラビアータ", romaji: "pennearabia-ta" },
    { category: "italy", ja: "クアトロフォルマッジ", romaji: "kuatoroforumajji" },
    { category: "italy", ja: "バーニャカウダ", romaji: "ba-nyakauda" },
    { category: "italy", ja: "アクアパッツァ", romaji: "akuapattsa" },
    { category: "italy", ja: "ジェラート", romaji: "jera-to" },
    { category: "italy", ja: "カルパッチョ", romaji: "karupaccshio" },
    { category: "italy", ja: "ニョッキ", romaji: "nyokki" },
    { category: "italy", ja: "パニーニ", romaji: "pani-ni" },
    { category: "italy", ja: "ビスコッティ", romaji: "bisukotti" },

    // スイーツ・カフェ (sweet)
    { category: "sweet", ja: "プリン", romaji: "purin" },
    { category: "sweet", ja: "パンケーキ", romaji: "panke-ki" },
    { category: "sweet", ja: "メロンパン", romaji: "meronpan" },
    { category: "sweet", ja: "イチゴパフェ", romaji: "ichigopafe" },
    { category: "sweet", ja: "サンドイッチ", romaji: "sandoicchi" },
    { category: "sweet", ja: "たい焼き", romaji: "taiyaki" },
    { category: "sweet", ja: "みたらし団子", romaji: "mitarashidango" },
    { category: "sweet", ja: "シュークリーム", romaji: "shu-kuri-mu" },
    { category: "sweet", ja: "ショートケーキ", romaji: "sho-toke-ki" },
    { category: "sweet", ja: "チョコレート", romaji: "chokore-to" },
    { category: "sweet", ja: "アイスクリーム", romaji: "aisukuri-mu" },
    { category: "sweet", ja: "ドーナツ", romaji: "do-natsu" },
    { category: "sweet", ja: "アップルパイ", romaji: "appurupai" },
    { category: "sweet", ja: "クッキー", romaji: "kukki-" },
    { category: "sweet", ja: "ゼリー", romaji: "zeri-" },
    { category: "sweet", ja: "チーズケーキ", romaji: "chi-zuke-ki" },
    { category: "sweet", ja: "マカロン", romaji: "makaron" },
    { category: "sweet", ja: "フィナンシェ", romaji: "finanshe" },
    { category: "sweet", ja: "エクレア", romaji: "ekurea" },
    { category: "sweet", ja: "モンブラン", romaji: "monburan" },
    { category: "sweet", ja: "タルト", romaji: "taruto" },
    { category: "sweet", ja: "ガトーショコラ", romaji: "gato-shokora" },
    { category: "sweet", ja: "わらび餅", romaji: "warabimochi" },
    { category: "sweet", ja: "あんみつ", romaji: "anmitsu" },
    { category: "sweet", ja: "おはぎ", romaji: "ohagi" },
    { category: "sweet", ja: "水羊羹", romaji: "mizuyoukan" },
    { category: "sweet", ja: "焼き芋", romaji: "yakiimo" },
    { category: "sweet", ja: "フレンチトースト", romaji: "furenchito-suto" },
    { category: "sweet", ja: "クレープ", romaji: "kure-pu" },
    { category: "sweet", ja: "ワッフル", romaji: "waffuru" },
    { category: "sweet", ja: "シフォンケーキ", romaji: "shifonke-ki" },
    { category: "sweet", ja: "どら焼き", romaji: "dorayaki" },
    { category: "sweet", ja: "大福", romaji: "daifuku" },
    { category: "sweet", ja: "チュロス", romaji: "churosu" },
    { category: "sweet", ja: "ロールケーキ", romaji: "ro-ruke-ki" },

    // アジアンエスニック (asia)
    { category: "asia", ja: "テンペ", romaji: "tenpe" },
    { category: "asia", ja: "ビビンバ", romaji: "bibinba" },
    { category: "asia", ja: "タコライス", romaji: "takoraisu" },
    { category: "asia", ja: "チヂミ", romaji: "chijimi" },
    { category: "asia", ja: "トッポギ", romaji: "toppogi" },
    { category: "asia", ja: "サムギョプサル", romaji: "samugyopusaru" },
    { category: "asia", ja: "生春巻き", romaji: "namaharumaki" },
    { category: "asia", ja: "トムヤムクン", romaji: "tomuyamukun" },
    { category: "asia", ja: "ガパオライス", romaji: "gapaoraisu" },
    { category: "asia", ja: "ナシゴレン", romaji: "nashigoren" },
    { category: "asia", ja: "タンドリーチチキン", romaji: "tandori-chikin" },
    { category: "asia", ja: "グリーンカレー", romaji: "guri-nka-re-" },
    { category: "asia", ja: "パッタイ", romaji: "pattai" },
    { category: "asia", ja: "フォー", romaji: "fo-" },
    { category: "asia", ja: "スンドゥブ", romaji: "sundubu" },
    { category: "asia", ja: "タッカルビ", romaji: "takkarubi" },
    { category: "asia", ja: "ヤンニョムチキン", romaji: "yannyomuchikin" },
    { category: "asia", ja: "キンパ", romaji: "kinpa" },
    { category: "asia", ja: "冷麺", romaji: "reimen" },
    { category: "asia", ja: "サムゲタン", romaji: "samugetan" },
    { category: "asia", ja: "サテ", romaji: "sate" },
    { category: "asia", ja: "ミーゴレン", romaji: "mi-goren" },
    { category: "asia", ja: "バインミー", romaji: "bainmi-" },
    { category: "asia", ja: "ナン", romaji: "nan" },
    { category: "asia", ja: "キーマカレー", romaji: "ki-maka-re-" },
    { category: "asia", ja: "ビリヤニ", romaji: "biriyani" },

    // ヨーロピアン (europe)
    { category: "europe", ja: "たこ焼き", romaji: "takoyaki" }, 
    { category: "europe", ja: "から揚げ", romaji: "karaage" },
    { category: "europe", ja: "エビフライ", romaji: "ebifurai" },
    { category: "europe", ja: "コロッケ", romaji: "korokke" },
    { category: "europe", ja: "ローストビーフ", romaji: "ro-sutobi-fu" },
    { category: "europe", ja: "ロールキャベツ", romaji: "ro-rukyabetsu" },
    { category: "europe", ja: "チキン南蛮", romaji: "chikinnanban" },
    { category: "europe", ja: "コーンスープ", romaji: "ko-nsu-pu" },
    { category: "europe", ja: "ビーフシチュー", romaji: "bi-fushichu-" },
    { category: "europe", ja: "ポトフ", romaji: "potofu" },
    { category: "europe", ja: "タコス", romaji: "takosu" },
    { category: "europe", ja: "ナチョス", romaji: "nachosu" },
    { category: "europe", ja: "フィッシュアンドチップス", romaji: "fisshuandochippusu" },
    { category: "europe", ja: "パエリア", romaji: "paeria" },
    { category: "europe", ja: "アヒージョ", romaji: "ahi-jo" },
    { category: "europe", ja: "ミートパイ", romaji: "mi-topai" },
    { category: "europe", ja: "チーズフォンデュ", romaji: "chi-zufondyu" },
    { category: "europe", ja: "ボルシチ", romaji: "borushichi" },
    { category: "europe", ja: "シュニッツェル", romaji: "shunittseru" },
    { category: "europe", ja: "キッシュ", romaji: "kisshu" },
    { category: "europe", ja: "エスカルゴ", romaji: "esukarugo" },
    { category: "europe", ja: "ソーセージ", romaji: "so-se-ji" },
    { category: "europe", ja: "プレッツェル", romaji: "purettseru" },
    { category: "europe", ja: "ザワークラウト", romaji: "zawa-kurauto" },
    { category: "europe", ja: "パテ", romaji: "pate" },

    // 宇宙の謎グルメ (space)
    { category: "space", ja: "火星パフェ", romaji: "kaseipafe" },
    { category: "space", ja: "スペースナポリタン", romaji: "supe-sunaporitan" },
    { category: "space", ja: "銀河チャーハン", romaji: "gingachashan" },
    { category: "space", ja: "流星おにぎり", romaji: "ryuseionigiri" },
    { category: "space", ja: "ブラックホール冷麺", romaji: "burakkuho-rureimen" },
    { category: "space", ja: "アンドロメダステーキ", romaji: "andoromedasute-ki" },
    { category: "space", ja: "ビッグバンバーガー", romaji: "biggubanba-ga-" },
    { category: "space", ja: "超新星バニラアイス", romaji: "choushinnseibaniraaisu" },
    { category: "space", ja: "コズミックピザ", romaji: "kozumikkupiza" },
    { category: "space", ja: "星屑ジュース", romaji: "hoshikuzuju-su" },
    { category: "space", ja: "エイリアンラーメン", romaji: "eirianra-men" },
    { category: "space", ja: "隕石ステーキ", romaji: "insekisute-ki" },
    { category: "space", ja: "サターンドーナツ", romaji: "sata-ndo-natsu" },
    { category: "space", ja: "ネビュラグラタン", romaji: "nebyuraguratan" },
    { category: "space", ja: "パルサーオムライス", romaji: "parusa-omuraisu" },
    { category: "space", ja: "ワームホールスープ", romaji: "wa-muho-rusu-pu" },
    { category: "space", ja: "プラズマゼリー", romaji: "purazumazeri-" },
    { category: "space", ja: "ギャラクシーサンド", romaji: "gyarakuxi-sando" },
    { category: "space", ja: "無重力コロッケ", romaji: "mujuuryokukorokke" },
    { category: "space", ja: "ダークマターカレー", romaji: "da-kumata-ka-re-" }
];